### PR TITLE
Add  acceptInsecureCerts capability for Firefox geckodriver

### PR DESCRIPTION
**Pull request by yigitozkavci**
Hi there!

After I got issues about untrusted warning on Firefox whenever I visit a website with self-signed SSL cert, I set the `acceptInsecureCerts` (which is documented [here](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities)) to `True` and made it work.

I think it should be a settable capability option for users who are using `geckodriver` with Firefox >=52 (https://github.com/mozilla/geckodriver/pull/632/commits/f86df5da6f84f56c0f0be8ced23de3025aba2176#diff-881ab48c5bc67f4e8c9d3ce5d7221613R109) binary.

### CODE REVIEW

**Comment by kallisti-dev** [comment]
Would it be possible to move this to the Firefox constructor? I don't like the idea of cluttering the primary capabilities record with browser specific options.

**Comment by yigitozkavci** [comment]
I'll give it a shot 👍

**Comment by yigitozkavci** [comment]
I guess it's cleaner this way. Can you take a look at it again @kallisti-dev ?

**Comment by kallisti-dev** [comment]
Looks good. Thanks for the contribution!

**Pull request merged**
