### PR TITLE
Add GHC CallStack support

### PR DESCRIPTION
**Pull request by thomasjm**
Hello -- this is kind of rough so I'm very open to feedback/other ideas how to do it.

Background: I was getting aggravated that sometimes it's impossible to tell where a given `FailedCommand` came from in my tests. Sometimes you can tell from the Selenium exception included in the `FailedCommand`, but sometimes not -- I was especially having trouble with an `ElementNotVisibleException` being thrown when I had code like the following

```
findElem (ByCSS ".foo") >>= click
findElem (ByCSS ".bar") >>= click
findElem (ByCSS ".baz") >>= click
```

I always ended up using print debugging to figure out which of the lines was actually the problem.

Now that GHC has better support for stacktraces, I thought I'd try plumbing the `CallStack` machinery through the WebDriver calls. This basically just means sprinkling `HasCallStack` everywhere, which GHC uses to pass a magical implicit parameter with call stack information.

When an exception actually occurs, the call stack is packaged up in an extra field I added to `FailedCommand`, so that upstream test frameworks (like `hspec-webdriver`) can present the offending line number nicely. (I realize this will probably break a lot of code that catches `FailedCommand` but wasn't sure how else to pass the information. Maybe inside `FailedCommandInfo`, even though that seems more like "the thing you get back from Selenium.")

Anyway, this is working well enough for my purposes now and I thought it might be useful to merge.

### CODE REVIEW

**Comment by kallisti-dev** [comment]
Changes look good. Next release will break the API anyway, so I don't see an issue with breaking compatibility with the old exception API.

**Comment by thomasjm** [comment]
Cool, thanks! Note that this PR didn't break API compatibility after all -- a later commit changed it to just push stack frames onto the existing stack frames list.

**Comment by kallisti-dev** [comment]
Hm, I'm having second thoughts on requiring ConstraintKinds since I believe that will break compatibility with anything before GHC 8. Eventually I do plan to break compatibility with 7.x with the upcoming Selenium API changes, but I'm not sure if I want to do that just yet.

**Comment by thomasjm** [comment]
I don't believe this PR introduced `ConstraintKinds`...

**Comment by kallisti-dev** [comment]
Travis builds are failing on it for GHC < 8.0. See https://travis-ci.org/kallisti-dev/hs-webdriver/builds/300688207

**Comment by kallisti-dev** [comment]
For GHC 7.10
```
src/Test/WebDriver/Commands/Internal.hs:70:18:
    Non type-variable argument
      in the constraint: ?callStack::GHC.Stack.CallStack
    (Use FlexibleContexts to permit this)
    In the type signature for ‘doSessCommand’:
      doSessCommand :: (HasCallStack,
                        WebDriver wd,
                        ToJSON a,
                        FromJSON b) =>
                       Method -> Text -> a -> wd b
Failed to install webdriver-0.8.5
cabal: Error: some packages failed to install:
webdriver-0.8.5 failed during the building phase. The exception was:
ExitFailure 1
```

For GHC < 7.10
```
src/Test/WebDriver/Commands/Internal.hs:70:18:
    Illegal tuple constraint: HasCallStack
      (Use -XConstraintKinds to permit this)
    In the type signature for `doSessCommand':
      doSessCommand :: (HasCallStack,
                        WebDriver wd,
                        ToJSON a,
                        FromJSON b) =>
                       Method -> Text -> a -> wd b
```

**Pull request merged**
