### PR TITLE
Added useful wait combinators

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @kallisti-dev !

Thanks for this nifty library, it's what convinced me to even trying writing UI tests in Haskell at work :wink: 

This PR ships two useful combinator I have extracted from some real world code, and finding them extremely helpful I thought about issuing a PR.

They are `waitUntilStale` and `waitUntilInvisible` and I've put extensive documentation around them, so I will leave the description of what the do for you to read in the haddock comments.

In a nutshell they helped me cleaning my test suite by a lot of explicit `threadDelay` and `waitUntil`, and they made my test suite much more reliable.

A note on formatting: I have an Emacs post-save hook which sorts and aligns the imports, that explains the noise in the diffs. I know this is opinionated and you might not like it, so I'm happy to restore the imports to their old nature!

Last but not least, I enabled `-fno-warn-type-defaults` to get rid of the super annoying "Defaulting to type Integer" for the usage of `threadDelay` in those combinators.

Let me know what you think and if there is something I can do to make this mergeable!

As everybody has different conventions and preferences or whether to bump or not the version of the library in the `cabal` manifest, I simply refrained from doing that.

Thank you!

Alfredo

### CODE REVIEW

**Comment by kallisti-dev** [comment]
Thanks for the detailed pull request @adinapoli. Currently the library has an `expectNotStale` function. What do you think about including a `expectStale` function to compliment `expectNotStale`?

Basically instead of writing:
```hs
do 
  waitUntilStale someElement
  waitUntil 10 myWaitCode
```
You write:

```hs
waitUntil 10 $ do
  expectStale someElement
  myWaitCode
```
A key difference here is that, because we're using the generalized 'waitUntil' combinator, we get a `Timeout` exception instead of a hang. This is generally good for tests, where we want to avoid hangs, but perhaps there are situations where you want the indefinite hang? I'm not sure. Indefinite variants of the `wait` family of functions might be useful to avoid ugly code like `waitUntil 999999999` and such.

Another angle of reasoning is that `expectStale` (and `expectVisible`) fits into our growing zoo of `expect*` functions, rather than creating a new zoo of `wait*` functions for specific conditions. I believe `waitUntil` and `waitWhile` should be sufficient for all purposes as long as there are appropriate `expect` functions available to handle all scenarios. This cleanly distinguishes `wait*` functions as timing control structures, while `expect*` functions are used to handle conditions.

It's really a shame to not accept clean well-documented code though. Perhaps there's room in our zoo for both types of functions?  I think if I wrote a Haskell-specific guide to explicit waits and expected conditions it would help new users become familiar with the codebase despite the proliferation of functions.

**Comment by adinapoli** [comment]
Hey @kallisti-dev !

It's all good, I think this kind of discussions are extremely helpful to make this library even better, and that's what counts, not my ego :stuck_out_tongue_winking_eye: 

Let me try to reply by points to explain my reasoning:

> Currently the library has an expectNotStale function. 

Yes, I know! In fact, I was on the fence about issuing this PR on not, due to your aforementioned
function. But as you have already pointed out, `expectNotStale` can be used only in conjunction with 
an explicit wait and, as you will probably have guessed by now, I'm not particularly found of them :wink: 
Am I right in thinking this? Consider it's 9AM here in Rome and I still didn't have my :coffee: , so excuse my caffeine-deprived brain!

> A key difference here is that, because we're using the generalized 'waitUntil' combinator, we get a Timeout exception instead of a hang. This is generally good for tests, where we want to avoid hangs, but perhaps there are situations where you want the indefinite hang? I'm not sure.

I suspect here it's just a different school of thoughts perhaps. Personally, I find super ugly to have my test suite ridden with explicit waits. I see 2 problems with that:

1. The driver (headless or not) one is using is subject to latency (example: loading of externally provided JS, waiting for backend replies, etc), and thus sometimes wait times we *explicitly* set might not be enough. This is unsettling for me because it means my tests might fail depending on some external agent.

2. With explicit wait we inflate our running times for no good reason; ideally I would personally prefer to have my tests take as long as it's needed, and no more! Thus polling is a better solution imho.

I **totally** agree with you that having tests which hangs sucks, especially if you have this is a CI server, but I consider this a _feature_. My opinion is that you write your tests with the invariant that, if you have no regressions, those should totally pass. If somethings hangs, it means a bug in your code! But I do agree that not having any kind of diagnostic is gross. Ideally my `waitUntil` functions should also catch a `Timeout` event and rethrow it, so that we wait for the globally set `implicitWait` and no more. What do you think about that? 

> Another angle of reasoning is that expectStale (and expectVisible) fits into our growing zoo of expect* functions, rather than creating a new zoo of wait* functions for specific conditions. I believe waitUntil and waitWhile should be sufficient for all purposes as long as there are appropriate expect functions available to handle all scenarios. This cleanly distinguishes wait* functions as timing control structures, while expect* functions are used to handle conditions.

That might be a good point API-wise, although my approach with testing libraries is that I like library authors to give me _lots_ of small building blocks, to craft my abstractions on top of it, and save me from some pain. As a UI-tester newbie, I struggled quite a lot on the concept of implicit waits and staleness, and I would have been super-glad to find a function is this library ready to be used and explaining to me *why* that was better than my naive explicit wait.

I hope this clarifies my reasoning behind this!

What do you think it's the best course of action here? Personally I don't mind keeping these functions in my codebase, but - as said - I think the real value here is the added knowledge they bring to the table (not that it's nothing groundbreaking!), which I wanted to share with the myself in the future, instead of keeping that to my own exclusive use :wink: 

Alfredo

**Comment by kallisti-dev** [comment]
> The driver (headless or not) one is using is subject to latency (example: loading of externally provided JS, waiting for backend replies, etc), and thus sometimes wait times we explicitly set might not be enough. This is unsettling for me because it means my tests might fail depending on some external agent.

This is a good point. I think this is a solid argument for providing wait functions with indefinite timers in situations where latency is high variance and/or unpredictable.

> With explicit wait we inflate our running times for no good reason; ideally I would personally prefer to have my tests take as long as it's needed, and no more! Thus polling is a better solution imho.

I'm not sure I understand what you mean. The way explicit waits work, the provided timeout value is a *maximum* wait time. The bracketed code is repeated until everything succeeds. So I don't see how this would incur any additional time.

> Ideally my waitUntil functions should also catch a Timeout event and rethrow it, so that we wait for the globally set implicitWait and no more. What do you think about that?

I was considering having a state monad that sits on top of `WD` that keeps track of a default timeout value (and perhaps some other useful state for explicit waits). This would be very similar to using the implicit wait as a default, but there are likely some situations where it would be clunky to use compared to something that automatically pulls from `setImplicitWait`. Not sure what the best approach here would be. A potential compromise would be to instead include a default wait value in `WDConfig` / `WDSession`. That way we don't have to add more monadic layers but we're also not pulling directly from the implicit wait which might need to be different for some reason. Also, if I recall correctly, there's some weirdness that can happen when using implicit waits in conjunction with explicit waits so keeping them separate is probably best.

**Comment by adinapoli** [comment]
Hey @kallisti-dev ! Lots of good points and food for thoughts! 

Regarding the second half of your reply, it looks like it's meaty enough to be outsourced into a separate ticket for discussion (happy to do that, if you're lazy 😉 ). Regarding the first half, in particular the first paragraph, it seems you are converging with me towards to idea of having a small API for implicit wait (essentially the ones I have added). Do you think we could merge this PR or more work/reorganisation is needed?

Thank you!

**Comment by kallisti-dev** [comment]
New issue created for that topic (#94).

As far as merging this pull request, I suspect not much of this code will actually survive the future feature additions. If you look at the new proposal(s) you'll see why. I think it would be best to keep this pull request on hold until the new stuff is in.

Also, based on http://stackoverflow.com/questions/15164742/combining-implicit-wait-and-explicit-wait-together-results-in-unexpected-wait-ti and some other sources I've read, some unexpected things can occur if you use `setImplicitWait` in conjunction with an explicit wait, so I don't think it would be wise to pull our default explicit wait timeout directly from the implicit wait value.

**Comment by adinapoli** [comment]
Perfect @kallisti-dev , that's fair enough! Will try to wrap my head around your new proposal and chime some time next week 😉

**Pull request closed without merging**
