### PR TITLE
Prohibit `http-client` from throwing exceptions for non 2xx response status codes

### PR DESCRIPTION
**Pull request by pavlosgi**

### CODE REVIEW

**Comment by kallisti-dev** [comment]
I need some clarification on the purpose of this change before I can accept
it. What issue does this solve?

**Comment by pavlosgi** [comment]
If selenium server responds with 500 http client will throw SomeException and the json response will never reach the handler you have that maps responses to FailedCommandType errors. With this patch http client does not throw SomeException in IO and the response flows through.

**Comment by pavlosgi** [comment]
I had 500s from selenium for errors such as StaleElementReference which is clearly a non exceptional thing

**Comment by pavlosgi** [comment]
Seems like this was fixed in http-client version 0.5.0 https://hackage.haskell.org/package/http-client-0.5.5/docs/Network-HTTP-Client.html#v:checkResponse. I will close this PR.

**Pull request closed without merging**
