### PR TITLE
Revert focus window parameter change

### PR DESCRIPTION
**Pull request by dten**
Not sure why this was changed but our selenium wants 'name'

### CODE REVIEW

**Comment by dten** [comment]
oopsie :)

**Comment by dten** [comment]
i meant this by the way :) https://github.com/tracsis/hs-webdriver/pull/21

**Comment by thomasjm** [comment]
Oh, what Selenium version expects "name" ?

**Comment by dten** [comment]
We've used 3.x and this package for years and they've seemingly always wanted name. Currently using 3.141.59 the last 3 build.

**Comment by dten** [comment]
The thing is I really confused things by opening this in the wrong repo though. This repo uses name which is correct

**Pull request closed without merging**
